image: deployer:latest
services:
  - docker:dind
before_script:
  - docker version
  - env
  - sh /root/gcp/active_dots.sh
stages:
  - build
  - release


variables:
  BUILD_IMAGE: gcr.io/dots-244203/ecommerce-provisioning:$CI_COMMIT_SHA
  TAG_IMAGE: gcr.io/dots-244203/ecommerce-provisioning:$CI_COMMIT_TAG
  RELEASE_IMAGE: gcr.io/dots-244203/ecommerce-provisioning:latest

build:
  stage: build
  script:
    - docker build -t $BUILD_IMAGE .
    - docker  push  $BUILD_IMAGE
  only:
    - master
  tags:
    - docker-builder
release:
  stage: release
  script:
    - docker tag $BUILD_IMAGE $TAG_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $TAG_IMAGE
    - docker push $RELEASE_IMAGE
    - cd k8s
    - sed -i "s/latest/"$CI_COMMIT_TAG"/g" uat-ecommerce-provisioning.yml
    - cat uat-ecommerce-provisioning.yml
    - kubectl apply -f uat-ecommerce-provisioning.yml
  only:
    - /^release-.*$/
  tags:
    - docker-builder




