apiVersion: apps/v1
kind: Deployment
metadata:
  name: spi
  labels:
    app: spi
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spi
  template:
    metadata:
      labels:
        app: spi
    spec:
      containers:
      - name: spi
        image: 163778996186.dkr.ecr.us-east-1.amazonaws.com/spi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000